#!/bin/bash

# dbus-tasmota-pv SetupHelper compatible setup script
# Tasmota power meter to Victron D-Bus PV inverter bridge

#### following line incorporates SetupHelper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources

packageName="dbus-tasmota-pv"

#### running manually - prompt for input
if [ "$scriptAction" == 'NONE' ]; then
    standardActionPrompt
fi

#### install
if [ "$scriptAction" == 'INSTALL' ]; then
    logMessage "Installing $packageName"
    
    # Create directories
    mkdir -p /data/dbus-tasmota-pv
    mkdir -p /var/log/dbus-tasmota-pv
    
    # Install Python script
    cp "$scriptDir/dbus-tasmota-pv.py" /data/dbus-tasmota-pv/
    chmod +x /data/dbus-tasmota-pv/*.py
fi

#### uninstall
if [ "$scriptAction" == 'UNINSTALL' ]; then
    logMessage "Uninstalling $packageName"
    
    # Remove Python scripts
    rm -rf /data/dbus-tasmota-pv
fi

# Install/uninstall services and finish
endScript INSTALL_SERVICE
