# SonarCloud configuration
# https://sonarqube.inria.fr/sonarqube/tutorials/ignore-rule/

# Ignore HTTP security warnings for Tasmota (device only supports HTTP, LAN traffic)
sonar.issue.ignore.multicriteria=e1

sonar.issue.ignore.multicriteria.e1.ruleKey=python:S5332
sonar.issue.ignore.multicriteria.e1.resourceKey=dbus-tasmota-pv.py
